tsv:
	edictor wordlist --dataset=../cldf/cldf-metadata.json --name=kochtukanoan --preprocessing=preprocessing.py
sqlite:
	edictor wordlist --sqlite --dataset=../cldf/cldf-metadata.json --name=kochtukanoan --preprocessing=preprocessing.py
